#!/usr/bin/env bash
# Adapted from TUFReplay's scripts/lib/context.sh for the independent renderer.
if [ "${RENDERER_CONTEXT_LOADED:-0}" = "1" ]; then
  return 0
fi
RENDERER_CONTEXT_LOADED=1
RENDERER_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RENDERER_PROJECT_ROOT="$(cd "$RENDERER_LIB_DIR/../.." && pwd)"

RENDERER_ENV_FILE="${RENDERER_ENV_FILE:-$RENDERER_PROJECT_ROOT/.env}"
if [ -f "$RENDERER_ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$RENDERER_ENV_FILE"
  set +a
fi

ADOFAI_DIR="${ADOFAI_DIR:-${GAME_DIR:-$HOME/Library/Application Support/Steam/steamapps/common/A Dance of Fire and Ice}}"
ADOFAI_MODS_DIR="${ADOFAI_MODS_DIR:-$ADOFAI_DIR/Mods}"
if [ -d "$ADOFAI_DIR/ADanceOfFireAndIce.app/Contents/Resources/Data/Managed" ]; then
  ADOFAI_MANAGED="${ADOFAI_MANAGED:-$ADOFAI_DIR/ADanceOfFireAndIce.app/Contents/Resources/Data/Managed}"
else
  ADOFAI_MANAGED="${ADOFAI_MANAGED:-$ADOFAI_DIR/A Dance of Fire and Ice_Data/Managed}"
fi
DOTNET_ROOT="${DOTNET_ROOT:-$HOME/.dotnet}"
DOTNET_ROOT_ARM64="${DOTNET_ROOT_ARM64:-$DOTNET_ROOT}"
DOTNET_EXE="${DOTNET_EXE:-$DOTNET_ROOT/dotnet}"
UNITY_MOD_MANAGER_DLL="${UNITY_MOD_MANAGER_DLL:-$ADOFAI_MANAGED/UnityModManager/UnityModManager.dll}"
HARMONY_DLL="${HARMONY_DLL:-$ADOFAI_MANAGED/UnityModManager/0Harmony.dll}"
ADOFAI_IPC_BUNDLE="${ADOFAI_IPC_BUNDLE:-$RENDERER_PROJECT_ROOT/vendor/adofai-ipc-runtime}"
RENDERER_BUILD_OUTPUT="${RENDERER_BUILD_DIR:-$RENDERER_PROJECT_ROOT/src/bin/Release/netstandard2.1}"
RENDERER_INSTALL_PATH="${RENDERER_INSTALL_DIR:-$ADOFAI_MODS_DIR/TUFReplay-Renderer}"
RENDERER_RELEASE_ROOT="${RENDERER_RELEASE_DIR:-$RENDERER_PROJECT_ROOT/Release}"
RENDERER_PACKAGE_STAGE="$RENDERER_RELEASE_ROOT/TUFReplay-Renderer"
RENDERER_PACKAGE_ZIP="$RENDERER_RELEASE_ROOT/TUFReplay-Renderer.zip"
FFMPEG_PATH="${FFMPEG_PATH:-ffmpeg}"

export RENDERER_PROJECT_ROOT RENDERER_ENV_FILE ADOFAI_DIR ADOFAI_MODS_DIR ADOFAI_MANAGED
export DOTNET_ROOT DOTNET_ROOT_ARM64 DOTNET_EXE UNITY_MOD_MANAGER_DLL HARMONY_DLL ADOFAI_IPC_BUNDLE
export RENDERER_BUILD_OUTPUT RENDERER_INSTALL_PATH RENDERER_RELEASE_ROOT RENDERER_PACKAGE_STAGE RENDERER_PACKAGE_ZIP FFMPEG_PATH
